// Generated by scripts/generate_design_contract.py. Do not edit.
package com.pcosina.app.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object GeneratedColors {
    val Pink = Color(0xFFFC6B7D)
    val DeepRose = Color(0xFF8C3A45)
    val SoftPink = Color(0xFFFFE4E8)
    val LightPink = Color(0xFFFFB4BC)
    val Surface = Color(0xFFFFF6F8)
    val SurfaceAlt = Color(0xFFFFF0F3)
    val Midnight = Color(0xFF2B1B20)
    val Muted = Color(0xFF5D4A50)
    val Info = Color(0xFF2E6ACF)
    val Success = Color(0xFF2E7D32)
    val Blush = Color(0xFFF89CAD)
    val BlushStrong = Color(0xFFF45F7E)
    val BlushSurface = Color(0xFFFDECEF)
    val BlushBorder = Color(0xFFC8B6BB)
    val RoseShadow = Color(0xFF9E5968)
    val Outline = Color(0xFFE4D7DB)
    val Danger = Color(0xFFB3261E)
    val Warning = Color(0xFF8B5B12)
    val White = Color(0xFFFFFFFF)
    val Black = Color(0xFF000000)
}

object GeneratedSpacing {
    val SectionGap = 14.dp
    val SectionHeaderGap = 12.dp
    val CardContentGap = 10.dp
    val CardContentPadding = 14.dp
    val MicroGap = 1.dp
}

object GeneratedRadii {
    val ExtraSmall = 6.dp
    val Small = 8.dp
    val Medium = 12.dp
    val Large = 16.dp
    val ExtraLarge = 24.dp
    val Pill = 999.dp
}

object GeneratedBreakpoints {
    const val Compact = 380
    const val WebMobile = 680
    const val WebTablet = 960
}

object GeneratedMotion {
    const val SplashAutoAdvance = 2500
    const val SplashPulse = 1100
    const val SplashFrameProbeWindow = 800
    const val ProfileStepSlide = 200
    const val ProfileStepFade = 120
    const val RecipeInitialRevealDelay = 44
    const val RecipeFadeIn = 190
    const val RecipeItemStaggerStep = 22
    const val RecipeItemStaggerMax = 110
    const val RecipeItemFadeIn = 165
    const val RecipeImpactReveal = 160
    const val SkeletonPulse = 1000
    const val DashboardRingProgress = 260
    const val MetricGaugeProgress = 520
    const val MetricBarProgress = 420
    const val FocusChipScale = 180
    const val FocusHintFade = 180
    const val FocusPanelSwap = 220
    const val FocusPanelScale = 240
    const val HeaderDrift = 3400
    const val HeaderGlow = 2600
    const val EmptyStateFloat = 3200
    const val EmptyStateGlow = 2200
    const val StickyActionReveal = 200
    const val PrimaryActionState = 180
    const val ExpandableChevron = 180
    const val ExpandableContent = 220
    const val JumpToTodayReveal = 150
    const val MotionFrameProbeWindow = 900
    const val FrameJankThreshold = 24
    const val FocusChipSelected = 1.03f
}

val GeneratedShapes = Shapes(
    extraSmall = RoundedCornerShape(GeneratedRadii.ExtraSmall),
    small = RoundedCornerShape(GeneratedRadii.Small),
    medium = RoundedCornerShape(GeneratedRadii.Medium),
    large = RoundedCornerShape(GeneratedRadii.Large),
    extraLarge = RoundedCornerShape(GeneratedRadii.ExtraLarge),
)

val GeneratedTypography = Typography(
    headlineLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.SemiBold,
        fontSize = 28.sp,
        lineHeight = 34.sp,
        letterSpacing = -0.5.sp
    ),
    headlineMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.SemiBold,
        fontSize = 24.sp,
        lineHeight = 30.sp,
        letterSpacing = -0.3.sp
    ),
    headlineSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.SemiBold,
        fontSize = 20.sp,
        lineHeight = 26.sp,
        letterSpacing = 0.sp
    ),
    titleLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Bold,
        fontSize = 20.sp,
        lineHeight = 26.sp,
        letterSpacing = 0.sp
    ),
    titleMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.SemiBold,
        fontSize = 18.sp,
        lineHeight = 24.sp,
        letterSpacing = 0.sp
    ),
    titleSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 16.sp,
        lineHeight = 22.sp,
        letterSpacing = 0.sp
    ),
    bodyLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = 16.sp,
        lineHeight = 24.sp,
        letterSpacing = 0.sp
    ),
    bodyMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        letterSpacing = 0.sp
    ),
    bodySmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 18.sp,
        letterSpacing = 0.sp
    ),
    labelLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 14.sp,
        lineHeight = 18.sp,
        letterSpacing = 0.sp
    ),
    labelMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.sp
    ),
    labelSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 11.sp,
        lineHeight = 14.sp,
        letterSpacing = 0.sp
    )
)
