services:
  - type: web
    name: pcosina-backend
    runtime: python
    branch: dev
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 2 -t 120 -b 0.0.0.0:$PORT main:app
    healthCheckPath: /health
