"""Generate Android and web design tokens and verify screen parity metadata."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
TOKENS_PATH = ROOT / "design-system" / "tokens.json"
PARITY_PATH = ROOT / "design-system" / "screen-parity.json"
KOTLIN_PATH = ROOT / "app" / "src" / "main" / "java" / "com" / "pcosina" / "app" / "ui" / "theme" / "GeneratedDesignTokens.kt"
CSS_PATH = ROOT / "web" / "src" / "generated" / "design-tokens.css"


def pascal(name: str) -> str:
    return name[:1].upper() + name[1:]


def kebab(name: str) -> str:
    chars: list[str] = []
    for char in name:
        if char.isupper():
            chars.extend(("-", char.lower()))
        else:
            chars.append(char)
    return "".join(chars)


def kotlin_color(hex_value: str) -> str:
    return f"Color(0xFF{hex_value.lstrip('#').upper()})"


def render_kotlin(tokens: dict) -> str:
    colors = "\n".join(
        f"    val {pascal(name)} = {kotlin_color(value)}"
        for name, value in tokens["colors"].items()
    )
    spacing = "\n".join(
        f"    val {pascal(name)} = {value}.dp"
        for name, value in tokens["spacingDp"].items()
    )
    radii = "\n".join(
        f"    val {pascal(name)} = {value}.dp"
        for name, value in tokens["radiiDp"].items()
    )
    breakpoints = "\n".join(
        f"    const val {pascal(name)} = {value}"
        for name, value in tokens["breakpointsDp"].items()
    )
    motion = "\n".join(
        f"    const val {pascal(name)} = {value}"
        for name, value in tokens["motionMs"].items()
    )
    scales = "\n".join(
        f"    const val {pascal(name)} = {value}f"
        for name, value in tokens["scales"].items()
    )
    typography_rows = []
    for name, spec in tokens["typographySp"].items():
        typography_rows.append(
            f"""    {name} = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.{spec["weight"]},
        fontSize = {spec["size"]}.sp,
        lineHeight = {spec["lineHeight"]}.sp,
        letterSpacing = {spec["letterSpacing"]}.sp
    )"""
        )
    typography = ",\n".join(typography_rows)
    return f"""// Generated by scripts/generate_design_contract.py. Do not edit.
package com.pcosina.app.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object GeneratedColors {{
{colors}
}}

object GeneratedSpacing {{
{spacing}
}}

object GeneratedRadii {{
{radii}
}}

object GeneratedBreakpoints {{
{breakpoints}
}}

object GeneratedMotion {{
{motion}
{scales}
}}

val GeneratedShapes = Shapes(
    extraSmall = RoundedCornerShape(GeneratedRadii.ExtraSmall),
    small = RoundedCornerShape(GeneratedRadii.Small),
    medium = RoundedCornerShape(GeneratedRadii.Medium),
    large = RoundedCornerShape(GeneratedRadii.Large),
    extraLarge = RoundedCornerShape(GeneratedRadii.ExtraLarge),
)

val GeneratedTypography = Typography(
{typography}
)
"""


def render_css(tokens: dict) -> str:
    rows = ["/* Generated by scripts/generate_design_contract.py. Do not edit. */", ":root {"]
    for name, value in tokens["colors"].items():
        rows.append(f"  --pcosina-{kebab(name)}: {value.lower()};")
    for name, value in tokens["spacingDp"].items():
        rows.append(f"  --space-{kebab(name)}: {value}px;")
    for name, value in tokens["radiiDp"].items():
        rows.append(f"  --radius-{kebab(name)}: {value}px;")
    for name, value in tokens["breakpointsDp"].items():
        rows.append(f"  --breakpoint-{kebab(name)}: {value}px;")
    for name, value in tokens["motionMs"].items():
        rows.append(f"  --motion-{kebab(name)}: {value}ms;")
    for name, value in tokens["scales"].items():
        rows.append(f"  --scale-{kebab(name)}: {value};")
    for name, spec in tokens["typographySp"].items():
        prefix = f"--type-{kebab(name)}"
        rows.extend(
            (
                f"  {prefix}-size: {spec['size']}px;",
                f"  {prefix}-line-height: {spec['lineHeight']}px;",
                f"  {prefix}-letter-spacing: {spec['letterSpacing']}px;",
            )
        )
    rows.append("}")
    return "\n".join(rows) + "\n"


def validate_parity() -> list[str]:
    data = json.loads(PARITY_PATH.read_text(encoding="utf-8"))
    errors: list[str] = []
    seen: set[str] = set()
    for screen in data.get("screens", []):
        screen_id = str(screen.get("id") or "")
        if not screen_id or screen_id in seen:
            errors.append(f"invalid or duplicate screen id: {screen_id!r}")
        seen.add(screen_id)
        for key in ("androidAuthority", "webAuthority", "webTest"):
            raw = str(screen.get(key) or "")
            path, _, marker = raw.partition("#")
            if not path or not (ROOT / path).is_file():
                errors.append(f"{screen_id}: missing {key} file {path!r}")
            elif marker and marker not in (ROOT / path).read_text(encoding="utf-8"):
                errors.append(f"{screen_id}: {key} marker {marker!r} not found in {path}")
        if not screen.get("requiredInteractions"):
            errors.append(f"{screen_id}: requiredInteractions must not be empty")
    return errors


def authority_content(raw: str) -> bytes:
    path_text, _, marker = raw.partition("#")
    path = ROOT / path_text
    content = path.read_text(encoding="utf-8")
    if not marker:
        return content.encode("utf-8")
    pattern = re.compile(
        rf"^(?:export\s+)?function\s+{re.escape(marker)}\b",
        flags=re.MULTILINE,
    )
    match = pattern.search(content)
    if not match:
        raise ValueError(f"marker {marker!r} not found in {path_text}")
    next_match = re.compile(r"^(?:export\s+)?function\s+[A-Z]\w*\b", flags=re.MULTILINE).search(
        content,
        match.end(),
    )
    end = next_match.start() if next_match else len(content)
    return content[match.start():end].encode("utf-8")


def authority_hash(raw: str) -> str:
    return hashlib.sha256(authority_content(raw)).hexdigest()


def update_or_validate_parity_hashes(update: bool, allow_one_sided: bool) -> list[str]:
    data = json.loads(PARITY_PATH.read_text(encoding="utf-8"))
    errors: list[str] = []
    changed = False
    for screen in data.get("screens", []):
        screen_id = str(screen.get("id") or "")
        try:
            android_hash = authority_hash(str(screen["androidAuthority"]))
            web_hash = authority_hash(str(screen["webAuthority"]))
        except (KeyError, ValueError) as exc:
            errors.append(f"{screen_id}: {exc}")
            continue
        recorded = screen.get("sourceFingerprints") or {}
        android_changed = bool(recorded) and recorded.get("android") != android_hash
        web_changed = bool(recorded) and recorded.get("web") != web_hash
        if update:
            if recorded and android_changed != web_changed and not allow_one_sided:
                errors.append(
                    f"{screen_id}: one-sided UI change detected; update Android and web together "
                    "or use --allow-one-sided-parity only with an explicit reviewed exception"
                )
                continue
            next_value = {"android": android_hash, "web": web_hash}
            if recorded != next_value:
                screen["sourceFingerprints"] = next_value
                changed = True
        elif recorded != {"android": android_hash, "web": web_hash}:
            errors.append(f"{screen_id}: source fingerprints are stale; refresh parity after updating both platforms")
    if update and changed and not errors:
        PARITY_PATH.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    return errors


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated outputs or parity metadata drift.")
    parser.add_argument("--update-parity", action="store_true", help="Refresh screen authority fingerprints.")
    parser.add_argument("--allow-one-sided-parity", action="store_true", help="Permit a reviewed one-platform exception.")
    args = parser.parse_args()
    tokens = json.loads(TOKENS_PATH.read_text(encoding="utf-8"))
    outputs = {
        KOTLIN_PATH: render_kotlin(tokens),
        CSS_PATH: render_css(tokens),
    }
    stale = [str(path.relative_to(ROOT)) for path, content in outputs.items() if not write_or_check(path, content, args.check)]
    errors = validate_parity()
    errors.extend(update_or_validate_parity_hashes(args.update_parity, args.allow_one_sided_parity))
    if stale:
        errors.append("stale generated files: " + ", ".join(stale))
    if errors:
        print("\n".join(f"ERROR: {error}" for error in errors), file=sys.stderr)
        return 1
    print("Design contract is valid." if args.check else "Generated shared Android and web design tokens.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
